### ISSUE TITLE
NullReferenceException when using GroupBy

### ISSUE THREAD

**Issue by mattpodwysocki** [Reactive-Extensions/Rx.NET#34]
Copied from https://rx.codeplex.com/workitem/69
(ConsoleApplication1.zip attachment not included)

I haven't come up with a repro for this outside of our full system, but I'll be sure to update it when I do. In the mean time, I'll do my best to describe the system and how we get to the point of seeing this exception and attach a project that has the relevant code but nothing that generates data. 

 We're using Rx inside our autoscaling service to window and aggregate the utilization statistics the other workloads in the system are publishing. Workloads publish statistics using the pub/sub capabilities of Redis and we use a pattern subscription to monitor all workloads from the central autoscaler. 

 The attached project has been simplified somewhat from our production code, but I believe everything relevant should still be there. There are two simplifications that I wouldn't expect to be relevant but I want to mention them in case they're useful in diagnosing the issue. 

 One last note, we normally expect events to come at 5 second intervals so we're configuring a 2 minute buffer with 5 seconds between buffers. However, when we used time-based buffering instead, the problem seemed to occur more frequently. 

 The following exception is thrown intermittently and when it occurs I seem to lose my subscriptions entirely.
```
Object reference not set to an instance of an object.
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Reactive.Linq.ObservableImpl.GroupBy`3._.OnNext(TSource value)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Reactive.AnonymousSafeObserver`1.OnError(Exception error)
   at System.Reactive.Linq.ObservableImpl.GroupBy`3._.Error(Exception exception)
   at System.Reactive.Linq.ObservableImpl.GroupBy`3._.OnNext(TSource value)
   at System.Reactive.Linq.ObservableImpl.Where`1._.OnNext(TSource value)
   at Apprenda.SaaSGrid.Topology.Utility.KernelPubSubExtensions.<>c__DisplayClass8`1.<PatternSubscribe>b__7(String sourcePath, T data) in c:\code\trunk\SaaSGrid\SaaSGrid.Topology\Apprenda\SaaSGrid\Topology\Utility\KernelPubSubExtensions.cs:line 39
   at Apprenda.Caching.Redis.RedisPubSub.<>c__DisplayClass5`1.<PatternSubscribe>b__3(String recievedTopic, Byte[] bytes) in c:\code\trunk\SaaSGrid\SaaSGrid.Caching\Apprenda\Caching\Redis\RedisPubSub.cs:line 63
   at BookSleeve.RedisSubscriberConnection.RaiseEvent(Action`2 handler, String key, RedisResult value) in c:\Dev\booksleeve\BookSleeve\RedisSubscriberConnection.cs:line 92
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Reactive.AnonymousSafeObserver`1.OnError(Exception error)
   at System.Reactive.Linq.ObservableImpl.Select`2._.OnError(Exception error)
   at System.Reactive.Linq.ObservableImpl.Buffer`1._.OnError(Exception error)
   at System.Reactive.Linq.ObservableImpl.Select`2._.OnError(Exception error)
   at System.Reactive.AutoDetachObserver`1.OnErrorCore(Exception exception)
   at System.Reactive.Subjects.Subject`1.Subscribe(IObserver`1 observer)
   at System.Reactive.Linq.GroupedObservable`2.SubscribeCore(IObserver`1 observer)
   at System.Reactive.ObservableBase`1.Subscribe(IObserver`1 observer)
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer)
   at System.Reactive.Producer`1.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard)
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer)
   at System.Reactive.Linq.ObservableImpl.Buffer`1.Run(IObserver`1 observer, IDisposable cancel, Action`1 setSink)
   at System.Reactive.Producer`1.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard)
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer)
   at System.Reactive.Producer`1.Run(IScheduler _, State x)
   at System.Reactive.Concurrency.ScheduledItem`2.InvokeCore()
   at System.Reactive.Concurrency.ScheduledItem`1.Invoke()
   at System.Reactive.Concurrency.CurrentThreadScheduler.Trampoline.Run(SchedulerQueue`1 queue)
   at System.Reactive.Concurrency.CurrentThreadScheduler.Schedule[TState](TState state, TimeSpan dueTime, Func`3 action)
   at System.Reactive.Concurrency.LocalScheduler.Schedule[TState](TState state, Func`3 action)
   at System.Reactive.Producer`1.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard)
   at Apprenda.Monitoring.Scaling.Autoscaler.ObserveStatistics() in c:\code\trunk\ApprendaCore\Apprenda.Monitoring\Scaling\Autoscaler.cs:line 66
   at Apprenda.Monitoring.Scaling.Autoscaler..ctor(Component component, IObservable`1 deploymentEventsByComponent, AutoscalingController controller, IObservable`1 statisticsStream) in c:\code\trunk\ApprendaCore\Apprenda.Monitoring\Scaling\Autoscaler.cs:line 50
   at Apprenda.Monitoring.Scaling.AutoscalingController.<>c__DisplayClass14.<HandleNewComponentStream>b__e(Guid _) in c:\code\trunk\ApprendaCore\Apprenda.Monitoring\Scaling\AutoscalingController.cs:line 70
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Apprenda.Monitoring.Scaling.AutoscalingController.HandleNewComponentStream(Guid componentId, IObservable`1 componentStream) in c:\code\trunk\ApprendaCore\Apprenda.Monitoring\Scaling\AutoscalingController.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Reactive.AnonymousSafeObserver`1.OnError(Exception error)
   at System.Reactive.Linq.ObservableImpl.Select`2._.OnError(Exception error)
   at System.Reactive.Linq.ObservableImpl.Buffer`1._.OnError(Exception error)
   at System.Reactive.Linq.ObservableImpl.Select`2._.OnError(Exception error)
   at System.Reactive.AutoDetachObserver`1.OnErrorCore(Exception exception)
   at System.Reactive.Subjects.Subject`1.Subscribe(IObserver`1 observer)
   at System.Reactive.Linq.GroupedObservable`2.SubscribeCore(IObserver`1 observer)
   at System.Reactive.ObservableBase`1.Subscribe(IObserver`1 observer)
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer)
   at System.Reactive.Producer`1.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard)
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer)
   at System.Reactive.Linq.ObservableImpl.Buffer`1.Run(IObserver`1 observer, IDisposable cancel, Action`1 setSink)
   at System.Reactive.Producer`1.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard)
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer)
   at System.Reactive.Producer`1.Run(IScheduler _, State x)
   at System.Reactive.Concurrency.ScheduledItem`2.InvokeCore()
   at System.Reactive.Concurrency.ScheduledItem`1.Invoke()
   at System.Reactive.Concurrency.CurrentThreadScheduler.Trampoline.Run(SchedulerQueue`1 queue)
   at System.Reactive.Concurrency.CurrentThreadScheduler.Schedule[TState](TState state, TimeSpan dueTime, Func`3 action)
   at System.Reactive.Concurrency.LocalScheduler.Schedule[TState](TState state, Func`3 action)
   at System.Reactive.Producer`1.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard)
   at Apprenda.Monitoring.Scaling.Autoscaler.ObserveStatistics() in c:\code\trunk\ApprendaCore\Apprenda.Monitoring\Scaling\Autoscaler.cs:line 66
   at Apprenda.Monitoring.Scaling.Autoscaler.ResetStatisticsWindow() in c:\code\trunk\ApprendaCore\Apprenda.Monitoring\Scaling\Autoscaler.cs:line 238
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Reactive.AnonymousSafeObserver`1.OnError(Exception error)
   at System.Reactive.Linq.ObservableImpl.Select`2._.OnError(Exception error)
   at System.Reactive.Linq.ObservableImpl.Buffer`1._.OnError(Exception error)
   at System.Reactive.Linq.ObservableImpl.Select`2._.OnError(Exception error)
   at System.Reactive.AutoDetachObserver`1.OnErrorCore(Exception exception)
   at System.Reactive.Subjects.Subject`1.Subscribe(IObserver`1 observer)
   at System.Reactive.Linq.GroupedObservable`2.SubscribeCore(IObserver`1 observer)
   at System.Reactive.ObservableBase`1.Subscribe(IObserver`1 observer)
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer)
   at System.Reactive.Producer`1.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard)
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer)
   at System.Reactive.Linq.ObservableImpl.Buffer`1.Run(IObserver`1 observer, IDisposable cancel, Action`1 setSink)
   at System.Reactive.Producer`1.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard)
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer)
   at System.Reactive.Producer`1.Run(IScheduler _, State x)
   at System.Reactive.Concurrency.ScheduledItem`2.InvokeCore()
   at System.Reactive.Concurrency.ScheduledItem`1.Invoke()
   at System.Reactive.Concurrency.CurrentThreadScheduler.Trampoline.Run(SchedulerQueue`1 queue)
   at System.Reactive.Concurrency.CurrentThreadScheduler.Schedule[TState](TState state, TimeSpan dueTime, Func`3 action)
   at System.Reactive.Concurrency.LocalScheduler.Schedule[TState](TState state, Func`3 action)
   at System.Reactive.Producer`1.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard)
   at Apprenda.Monitoring.Scaling.Autoscaler.ObserveStatistics() in c:\code\trunk\ApprendaCore\Apprenda.Monitoring\Scaling\Autoscaler.cs:line 66
```

**Comment by bartdesmet** [comment]
This is not a bug in Rx; the input sequence obtained via FromEvent is not obeying to the Rx grammar because it has no sequential nature in and of itself. The concurrency of the event "leaks" into the observable wrapper created by FromEvent. In order to get around this, use the Synchronize operator:

var statisticsObservable = Observable.FromEvent<Guid>(h => onDataReceived = h, h => onDataReceived = null).Synchronize();

It is debatable whether FromEvent should do this of itself and we've gone back and forth on this. The consensus was that importing existing sources of events should be as lightweight as possible, with synchronization composed on top if needed.

Hope this helps!
