### ISSUE TITLE
Exception when user changes system clock

### ISSUE THREAD

**Issue by mattpodwysocki** [Reactive-Extensions/Rx.NET#39]
Copied from https://rx.codeplex.com/workitem/60

When using an timer in Rx (Net), if the user changes the system clock back somewhere over a month an exception (`ArgumentOutOfRangeException`) is raised:
```
Time-out interval must be less than 2^32-2.
Parameter name: dueTm

Stack trace:
at System.Threading.Timer..ctor(TimerCallback callback, Object state, TimeSpan dueTime, TimeSpan period)
at System.Reactive.Concurrency.ConcurrencyAbstractionLayerImpl.Timer..ctor(Action`1 action, Object state, TimeSpan dueTime)
at System.Reactive.Concurrency.ConcurrencyAbstractionLayerImpl.StartTimer(Action`1 action, Object state, TimeSpan dueTime)
at System.Reactive.Concurrency.LocalScheduler.UpdateLongTermProcessingTimer()
at System.Reactive.Concurrency.LocalScheduler.EvaluateLongTermQueue(Object state)
at System.Reactive.Concurrency.LocalScheduler.SystemClockChanged(Object sender, SystemClockChangedEventArgs args)
at System.Reactive.PlatformServices.SystemClock.OnSystemClockChanged(Object sender, SystemClockChangedEventArgs e)
at System.Reactive.PlatformServices.PeriodicTimerSystemClockMonitor.TimeChanged()
at System.Reactive.Concurrency.ConcurrencyAbstractionLayerImpl.PeriodicTimer.Tick(Object state)
at System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.TimerQueueTimer.CallCallback()
at System.Threading.TimerQueueTimer.Fire()
at System.Threading.TimerQueue.FireNextTimers()
at System.Threading.TimerQueue.AppDomainTimerCallback()
```
The exception is unhandled and causes the host application to crash. 

 A related issue was reported on the Rx MSDN Forums back in 2011: 
◾ `BufferWithTime` exception when user changes system clock

**Comment by bartdesmet** [comment]
This does no longer reproduce. We have code in place that deals with this, cf. "dueCapped" in LocalScheduler.TimerQueue.cs.
