### ISSUE TITLE
.NET Core: 'At least one object must implement IComparable.'

### ISSUE THREAD

**Issue by roederja2** [Reactive-Extensions/Rx.NET#398]
Since I migrated from .Net 4.6.2 to dotnetcore 1.1 I get an Argument exception 'At least one object must implement IComparable.' It doesn't seem to have anything to do with my code.

```
   at System.Collections.Comparer.Compare(Object a, Object b)
   at System.Linq.EnumerableSorter`2.CompareAnyKeys(Int32 index1, Int32 index2)
   at System.Linq.EnumerableSorter`1.CompareKeys(Int32 index1, Int32 index2)
   at System.Linq.EnumerableSorter`1.QuickSort(Int32[] map, Int32 left, Int32 right)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__3.MoveNext()
   at System.Reactive.Linq.ObservableImpl.SelectMany`2.NoSelectorImpl.OnNext(TSource value)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Reactive.Stubs.<>c.<.cctor>b__2_1(Exception ex)
   at System.Reactive.AnonymousSafeObserver`1.OnError(Exception error)
   at System.Reactive.Linq.ObservableImpl.Do`1._.OnError(Exception error)
   at System.Reactive.Linq.ObservableImpl.SelectMany`2.NoSelectorImpl.OnNext(TSource value)
   at System.Reactive.Linq.ObservableImpl.ToArray`1._.OnCompleted()
   at System.Reactive.Linq.ObservableImpl.SelectMany`2._.Iter.OnCompleted()
   at System.Reactive.Linq.ObservableImpl.Catch`2._.OnCompleted()
   at System.Reactive.Linq.ObservableImpl.SelectMany`2._.Iter.OnCompleted()
   at System.Reactive.Linq.ObservableImpl.AsObservable`1._.OnCompleted()
   at System.Reactive.Subjects.AsyncSubject`1.OnCompleted()
   at System.Reactive.Linq.QueryLanguage.<>c__DisplayClass188_1`1.<ToAsync>b__1()
   at System.Reactive.Concurrency.Scheduler.Invoke(IScheduler scheduler, Action action)
   at System.Reactive.Concurrency.DefaultScheduler.<>c__DisplayClass5_0`1.<Schedule>b__0(Object _)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by roederja2** [comment]
It was my code after all... caused by an update of the NodaTime library. Just quite hard to figure out where the problem was.
