### ISSUE TITLE
Observable.Timer() and Observable.Interval() throw exception if period == 0 

### ISSUE THREAD

**Issue by mattpodwysocki** [Reactive-Extensions/Rx.NET#51]
Copied from https://rx.codeplex.com/workitem/13

Even though the documentation says period == 0 is supported:
```c#
/// <param name="period">Period to produce subsequent values. If this value is equal to TimeSpan.Zero, the timer will recur as fast as possible.</param>
Here is an example exception stack trace:
   at System.Reactive.Concurrency.ConcurrencyAbstractionLayerImpl.StartPeriodicTimer(Action action, TimeSpan period)
   at System.Reactive.Concurrency.DefaultScheduler.SchedulePeriodic[TState](TState state, TimeSpan period, Func`2 action)
   at System.Reactive.Concurrency.Scheduler.SchedulePeriodic_[TState](IScheduler scheduler, TState state, TimeSpan period, Func`2 action)
   at System.Reactive.Concurrency.Scheduler.SchedulePeriodic[TState](IScheduler scheduler, TState state, TimeSpan period, Func`2 action)
   at System.Reactive.Linq.Observαble.Timer.π.Run()
   at System.Reactive.Linq.Observαble.Timer.Run(IObserver`1 observer, IDisposable cancel, Action`1 setSink)
```
(remainder elided)
The issue seems to be this code in 
```c#
System.Reactive.Concurrency.ConcurrencyAbstractionLayerImpl.StartPeriodicTimer(Action action, TimeSpan period):
```
```c#
//
// MSDN documentation states the following:
//
//    "If period is zero (0) or negative one (-1) milliseconds and dueTime is positive, callback is invoked once;
//     the periodic behavior of the timer is disabled, but can be re-enabled using the Change method."
//
if (period <= TimeSpan.Zero)
    throw new ArgumentOutOfRangeException("period");
```
Even the comment seems to indicate Period==0 is allowed.

**Comment by bartdesmet** [comment]
This was fixed a while back; some additional tweaks have been made to support this for the ThreadPoolScheduler as well.
